# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  backend:
    image: demo-backend
    build:
      context: ./demo-backend
      dockerfile: ./Dockerfile
    ports:
      - 5188:5188
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
  frontend:
    image: demo-frontend
    build:
      context: ./demo-app
      dockerfile: ./Dockerfile
    ports:
      - 8080:80
